name: Another workflow for my Testing
on: push
jobs:
  build-job:
    name: Test action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out code
      run: echo Hello World
    - name: Courses.html Content
      run: cat Courses.html
