name: Another workflow for my Testing
on:
 workflow_dispatch:
 push:
  paths:
  - '!.github/**'

jobs:
  build-job:
    name: Test action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out code
      run: echo Hello World
    - name: courses.html Content
      run: cat courses.html
